### ISSUE TITLE
Create Logs Sink Connector for New Relic Log API

### ISSUE THREAD

**Issue by JimHagan** [newrelic/kafka-connect-newrelic#22]
# New Log Sink Connector Modeled After Event and Metric Connectors

- Support logs as a first class model in our Kafka Connect plugin. 
- This has high business value as it will give a more scalable log pipeline option for our our larger more sophisticated users and may be a cost effective alternative to S3/Kinesis/CloudWatch (at high scale).

**Comment by amoswood** [comment]
We would definitely use this, but I was thinking that there might be an alternative for this using logstash or something else right?

**Comment by maju6406** [comment]
@JimHagan @amoswood check out #31

**Comment by ericmittelhammer** [comment]
available since 1.1.  Cleaning up...
