### ISSUE TITLE
Build New Relic JAR Artifacts Via Github Actions

### ISSUE THREAD

**Issue by JimHagan** [newrelic/kafka-connect-newrelic#24]
- Identify which jars needed to be included
- Setup the CI code to do it
- Find a way to associated a reasonable README to document what each artifact does and basic installation instructions.

**Comment by ericmittelhammer** [comment]
Added in v2.0.0.
https://github.com/newrelic/kafka-connect-newrelic/blob/b732289f062aa1e551fa92b56e77140ca4b2d38d/.github/workflows/release.yml
