### ISSUE TITLE
Customer would like 2.3.0  available in Confluent Hub for download

### ISSUE THREAD

**Issue by wildcardlinux** [newrelic/kafka-connect-newrelic#62]
Customer would like 2.3.0  available in Confluent Hub for download.

https://www.confluent.io/hub/newrelic/newrelic-kafka-connector/ 

## Description

Customer cannot select version 2.3.0 from Confluent Hub

## Steps to Reproduce

Try to download previous version from https://www.confluent.io/hub/newrelic/newrelic-kafka-connector/ 

## Expected Behaviour

Can version 2.3.0 be a version available for download.

![Confluent_Downloads](https://github.com/newrelic/kafka-connect-newrelic/assets/49290076/71a1769d-7fb6-4f6c-9843-c15c803cd974)

**Comment by wildcardlinux** [comment]
https://github.com/newrelic/kafka-connect-newrelic/blob/db2eb1dda605d9c5f0b117adea7943f2252ef9b1/newrelic-kafka-connector/src/main/java/com/newrelic/telemetry/TelemetrySinkTask.java#L58

**Comment by benders** [comment]
Closing, since 2.3.3 is the current version on Confluent Hub now.
